"""QueryLog model for NLP audit trail.

Phase 1: Database Schema & Historical Data Ingestion
"""
from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, Date
from .base import Base, utcnow


class QueryLog(Base):
    """Audit trail of all SQL generated by the Claude API NLP interface."""
    __tablename__ = "query_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=utcnow, nullable=False, index=True)
    question_text = Column(Text, nullable=False)
    generated_sql = Column(Text, nullable=False)
    execution_time_ms = Column(Integer)
    row_count = Column(Integer)
    success = Column(Boolean, nullable=False)
    error_message = Column(Text)
    created_at = Column(DateTime, default=utcnow)


class ScrapeRun(Base):
    """Track scraper execution history for operational monitoring."""
    __tablename__ = "scrape_runs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    started_at = Column(DateTime, nullable=False)
    completed_at = Column(DateTime)
    mode = Column(String(20))         # "auto", "manual", "historical"
    season = Column(Integer)
    date_from = Column(Date)
    date_to = Column(Date)
    games_found = Column(Integer, default=0)
    games_loaded = Column(Integer, default=0)
    games_failed = Column(Integer, default=0)
    player_stats_loaded = Column(Integer, default=0)
    officials_loaded = Column(Integer, default=0)
    success = Column(Boolean, default=True)
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=utcnow)
